export type AccessTokenFlag =
  | "TOKEN_ADJUST_DEFAULT"
  | "TOKEN_ADJUST_GROUPS"
  | "TOKEN_ADJUST_PRIVILEGES"
  | "TOKEN_ADJUST_SESSIONID"
  | "TOKEN_ASSIGN_PRIMARY"
  | "TOKEN_DUPLICATE"
  | "TOKEN_EXECUTE"
  | "TOKEN_IMPERSONATE"
  | "TOKEN_QUERY"
  | "TOKEN_QUERY_SOURCE"
  | "TOKEN_READ"
  | "TOKEN_WRITE"
  | "TOKEN_ALL_ACCESS";
